# Generated by Django 5.2 on 2025-04-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField()),
                ('severity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=255, unique=True)),
                ('notification_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both')], default='both', max_length=50)),
            ],
        ),
    ]
