# Generated by Django 5.2 on 2025-04-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrule',
            name='frequency',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='threshold',
            field=models.IntegerField(default=1),
        ),
    ]
