# Generated by Django 5.2 on 2025-04-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationrule_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='failurelog',
            name='notification_method',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
