# Generated by Django 5.2 on 2025-04-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_failurelog_notification_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='failurelog',
            name='api_name',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
