# Generated by Django 5.2 on 2025-04-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_failurelog_api_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failurelog',
            name='notification_method',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both'), ('none', 'None')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='failurelog',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='critical', max_length=50),
        ),
    ]
